// <auto-generated />
using System;
using Library.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.DAL.Migrations
{
    [DbContext(typeof(TestDbForRememberContext))]
    [Migration("20260623134324_AddGenre")]
    partial class AddGenre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library.DAL.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("BIRTHDAY")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("SecondName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SECOND_NAME");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SURNAME");

                    b.HasKey("Id")
                        .HasName("PK__Autors__3214EC27B8BFA5B8");

                    b.ToTable("Autors");
                });

            modelBuilder.Entity("Library.DAL.Models.AutorsBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("AutorID");

                    b.Property<int?>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    b.HasKey("Id")
                        .HasName("PK__AutorsBo__3214EC275C6BF2A6");

                    b.HasIndex("AutorId");

                    b.HasIndex("BookId");

                    b.ToTable("AutorsBooks");
                });

            modelBuilder.Entity("Library.DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("AUTOR_ID");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CITY");

                    b.Property<int>("CodeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CodeTypeID");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("Genre")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("PublishCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PUBLISH_CODE");

                    b.Property<DateTime?>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Books__3214EC27BBE8AA0B");

                    b.HasIndex("AutorId");

                    b.HasIndex("CodeTypeId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Library.DAL.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id")
                        .HasName("PK__Document__3214EC2751C9425A");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("Library.DAL.Models.Librarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("Id")
                        .HasName("PK__Libraria__3214EC272A2A9F49");

                    b.ToTable("Librarians");
                });

            modelBuilder.Entity("Library.DAL.Models.PublusherType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Publusher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Publushe__3214EC2734FF1996");

                    b.ToTable("PublusherTypes");
                });

            modelBuilder.Entity("Library.DAL.Models.Reader", b =>
                {
                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DOCUMENT_NUMBER");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DOCUMENT_TYPE_ID");

                    b.Property<string>("Email")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SURNAME");

                    b.HasKey("Login")
                        .HasName("PK__Readers__E39E26647265DE1F");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("Library.DAL.Models.AutorsBook", b =>
                {
                    b.HasOne("Library.DAL.Models.Autor", "Autor")
                        .WithMany("AutorsBooks")
                        .HasForeignKey("AutorId")
                        .HasConstraintName("FK__AutorsBoo__Autor__02084FDA");

                    b.HasOne("Library.DAL.Models.Book", "Book")
                        .WithMany("AutorsBooks")
                        .HasForeignKey("BookId")
                        .HasConstraintName("FK__AutorsBoo__BookI__02FC7413");

                    b.Navigation("Autor");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Library.DAL.Models.Book", b =>
                {
                    b.HasOne("Library.DAL.Models.Autor", "Autor")
                        .WithMany("Books")
                        .HasForeignKey("AutorId")
                        .IsRequired()
                        .HasConstraintName("FK__Books__AUTOR_ID__7D439ABD");

                    b.HasOne("Library.DAL.Models.PublusherType", "CodeType")
                        .WithMany("Books")
                        .HasForeignKey("CodeTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Books__CodeTypeI__7E37BEF6");

                    b.Navigation("Autor");

                    b.Navigation("CodeType");
                });

            modelBuilder.Entity("Library.DAL.Models.Reader", b =>
                {
                    b.HasOne("Library.DAL.Models.DocumentType", "DocumentType")
                        .WithMany("Readers")
                        .HasForeignKey("DocumentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Readers__DOCUMEN__778AC167");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("Library.DAL.Models.Autor", b =>
                {
                    b.Navigation("AutorsBooks");

                    b.Navigation("Books");
                });

            modelBuilder.Entity("Library.DAL.Models.Book", b =>
                {
                    b.Navigation("AutorsBooks");
                });

            modelBuilder.Entity("Library.DAL.Models.DocumentType", b =>
                {
                    b.Navigation("Readers");
                });

            modelBuilder.Entity("Library.DAL.Models.PublusherType", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
