// <auto-generated />
using System;
using Library.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.DAL.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260625090231_AddReturnedDaysToBook")]
    partial class AddReturnedDaysToBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 3
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 4
                        });
                });

            modelBuilder.Entity("Library.DAL.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Fiom",
                            Name = "Oleg"
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Syropin",
                            Name = "Ivan",
                            SecondName = "Grozniy"
                        },
                        new
                        {
                            Id = 3,
                            LastName = "Syropin",
                            Name = "Vasiliy",
                            SecondName = "Krot"
                        });
                });

            modelBuilder.Entity("Library.DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishYear")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublisherTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ReturnedDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherTypeId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Kharkiv",
                            Count = 2,
                            Country = "Ukrain",
                            Genre = 1024,
                            Name = "C# for smart",
                            PublishYear = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherTypeId = 1,
                            ReturnedDays = 30
                        },
                        new
                        {
                            Id = 2,
                            City = "Kiev",
                            Count = 1,
                            Country = "Ukrain",
                            Genre = 16,
                            Name = "World Story",
                            PublishYear = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherTypeId = 2,
                            ReturnedDays = 30
                        },
                        new
                        {
                            Id = 3,
                            City = "Kiev",
                            Count = 5,
                            Country = "Ukrain",
                            Genre = 32,
                            Name = "Summer Time",
                            PublishYear = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherTypeId = 3,
                            ReturnedDays = 30
                        },
                        new
                        {
                            Id = 4,
                            Count = 2,
                            Country = "Poland",
                            Genre = 2,
                            Name = "Mgla",
                            PublishYear = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherTypeId = 1,
                            ReturnedDays = 30
                        });
                });

            modelBuilder.Entity("Library.DAL.Models.Librarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Librarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            Login = "Admin",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin1@gmail.com",
                            Login = "Admin1",
                            Password = "4567"
                        });
                });

            modelBuilder.Entity("Library.DAL.Models.PublisherCodeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PublisherCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PublishingCodeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PublisherCode = "ISBN"
                        },
                        new
                        {
                            Id = 2,
                            PublisherCode = "ISSN"
                        },
                        new
                        {
                            Id = 3,
                            PublisherCode = "ISRC"
                        },
                        new
                        {
                            Id = 4,
                            PublisherCode = "ISWC"
                        });
                });

            modelBuilder.Entity("Library.DAL.Models.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LibrarianId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LibrarianId");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DocumentNumber = "3354213",
                            DocumentType = 1,
                            Email = "reader@gmail.com",
                            LastName = "Lighter",
                            Login = "Reader",
                            Name = "Bob",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1993, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "777789",
                            DocumentType = 0,
                            Email = "rEAr@gmail.com",
                            LastName = "Zeroph",
                            Login = "Reader1",
                            Name = "Alex",
                            Password = "1423"
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("Library.DAL.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.DAL.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library.DAL.Models.Book", b =>
                {
                    b.HasOne("Library.DAL.Models.PublisherCodeType", "PublisherType")
                        .WithMany()
                        .HasForeignKey("PublisherTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublisherType");
                });

            modelBuilder.Entity("Library.DAL.Models.Reader", b =>
                {
                    b.HasOne("Library.DAL.Models.Librarian", null)
                        .WithMany("Readers")
                        .HasForeignKey("LibrarianId");
                });

            modelBuilder.Entity("Library.DAL.Models.Librarian", b =>
                {
                    b.Navigation("Readers");
                });
#pragma warning restore 612, 618
        }
    }
}
